### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by NotAFile** [xtreme8000/aof-opengl#80]
1. open game
2. close game

```
23:59:51 INFO  main.c:598: Game started!
23:59:52 INFO  main.c:608: Vendor: Intel Open Source Technology Center
23:59:52 INFO  main.c:609: Renderer: Mesa DRI Intel(R) Ivybridge Mobile
23:59:52 INFO  main.c:610: Version: 3.0 Mesa 18.3.3
23:59:52 INFO  chunk.c:54: 2 cores enabled for chunk generation
23:59:52 INFO  font.c:101: font texsize: 256:512px [size 36.000000] type: 0
23:59:52 INFO  font.c:101: font texsize: 256:256px [size 20.000000] type: 0
23:59:52 INFO  font.c:101: font texsize: 128:256px [size 18.000000] type: 0
23:59:52 INFO  font.c:101: font texsize: 256:256px [size 24.000000] type: 0
23:59:52 INFO  font.c:101: font texsize: 512:512px [size 43.740002] type: 0
23:59:52 INFO  font.c:101: font texsize: 256:256px [size 24.300001] type: 0
23:59:52 INFO  font.c:101: font texsize: 256:256px [size 21.870001] type: 0
23:59:52 INFO  font.c:101: font texsize: 256:512px [size 29.160000] type: 0
23:59:52 INFO  hud.c:1650: newest game version: v0.1.3
23:59:52 INFO  hud.c:1651: current game version: v0.1.3
23:59:52 INFO  font.c:101: font texsize: 256:256px [size 19.440001] type: 0
23:59:54 WARN  ping.c:109: Ping timeout on some server(s), retrying
23:59:54 WARN  ping.c:109: Ping timeout on some server(s), retrying
=================================================================
==7536==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61f00000ee50 at pc 0x7f3f7f686de7 bp 0x7f3f5c6b0b80 sp 0x7f3f5c6b0328
WRITE of size 96 at 0x61f00000ee50 thread T7
    #0 0x7f3f7f686de6 in __interceptor_memmove (/lib64/libasan.so.5+0x38de6)
    #1 0x4345fe in list_remove ../src/list.c:32
    #2 0x448f77 in ping_update ../src/ping.c:81
    #3 0x7f3f7f63458d in start_thread (/lib64/libpthread.so.0+0x858d)
    #4 0x7f3f7efd16a2 in clone (/lib64/libc.so.6+0xfd6a2)

0x61f00000ee50 is located 48 bytes to the left of 3072-byte region [0x61f00000ee80,0x61f00000fa80)
allocated by thread T0 here:
    #0 0x7f3f7f73dc88 in realloc (/lib64/libasan.so.5+0xefc88)
    #1 0x434577 in list_add ../src/list.c:21

Thread T7 created by T0 here:
    #0 0x7f3f7f69a043 in __interceptor_pthread_create (/lib64/libasan.so.5+0x4c043)
    #1 0x44941e in ping_start ../src/ping.c:176

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0x38de6) in __interceptor_memmove
Shadow bytes around the buggy address:
  0x0c3e7fff9d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff9d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff9d90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3e7fff9db0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3e7fff9dc0: fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa fa fa
  0x0c3e7fff9dd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff9de0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff9df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff9e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3e7fff9e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7536==ABORTING
```

**Comment by xtreme8000** [comment]
ping code was rewritten recently so probably fixed
